<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            ['name' => 'test1',
            'email' => 'test1@test.com',
            'sex' => '0',
            'age' => '25',
            'self_introduction' => 'test1です',
            'password' => Hash::make('11111111'),
            ],
            ['name' => 'Alvaro',
            'email' => 'user1@example.com',
            'sex' => '0',
            'age' => '30',
            'self_introduction' => 'Alvaroです',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'Elliot',
            'email' => 'user2@example.com',
            'sex' => '1',
            'age' => '28',
            'self_introduction' => 'Elliotです',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'Oliver',
            'email' => 'user3@example.com',
            'sex' => '0',
            'age' => '24',
            'self_introduction' => 'Oliverです',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'Elizabeth',
            'email' => 'user4@example.com',
            'sex' => '1',
            'age' => '43',
            'self_introduction' => 'Elizabethです',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'Cyrus',
            'email' => 'user5@example.com',
            'sex' => '1',
            'age' => '21',
            'self_introduction' => 'Cyrusです',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'James',
            'email' => 'user6@example.com',
            'sex' => '1',
            'age' => '27',
            'self_introduction' => 'Jamesです',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'Johnathan',
            'email' => 'user7@example.com',
            'sex' => '1',
            'age' => '33',
            'self_introduction' => 'Johnathanです',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'Daniel',
            'email' => 'user8@example.com',
            'sex' => '1',
            'age' => '31',
            'self_introduction' => 'Danielです',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'Melvin',
            'email' => 'user9@example.com',
            'sex' => '1',
            'age' => '21',
            'self_introduction' => 'Melvinです',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'Reilly',
            'email' => 'user10@example.com',
            'sex' => '1',
            'age' => '22',
            'self_introduction' => 'Reillyです',
            'password' => Hash::make('password123'),
            ],
        ]);
    }
}
